[project]
name = "dashboardvente"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Onivoid", email = "onivoid.tv@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "pandas>=3.0.5",
    "psycopg[binary]>=3.3.6",
    "requests>=2.34.2",
    "sqlalchemy>=2.0.54",
    "streamlit>=1.64.0",
    "uvicorn>=0.53.0",
]

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "back"
module-root = ""
